// <auto-generated />
using System;
using CIOT.Modules.Asset.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CIOT.Modules.Asset.Infrastructure.Migrations
{
    [DbContext(typeof(AssetDbContext))]
    partial class AssetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("asset")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CIOT.Modules.Asset.Domain.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("AcquisitionDate")
                        .HasColumnType("date")
                        .HasColumnName("acquisition_date");

                    b.Property<DateOnly?>("ActivationDate")
                        .HasColumnType("date")
                        .HasColumnName("activation_date");

                    b.Property<Guid?>("AssetTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_type_id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("EquipmentModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_model_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastConnectionAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_connection_at_utc");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<string>("OemSerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("oem_serial_number");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SapEquipmentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sap_equipment_number");

                    b.Property<string>("SapStatus")
                        .HasColumnType("text")
                        .HasColumnName("sap_status");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("text")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("TechnicalId")
                        .HasColumnType("text")
                        .HasColumnName("technical_id");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("SapEquipmentNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_assets_sap_equipment_number");

                    b.ToTable("assets", "asset");
                });

            modelBuilder.Entity("CIOT.Modules.Asset.Domain.AssetIdentifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("IdentifierType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identifier_type");

                    b.Property<string>("IdentifierValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identifier_value");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("text")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.HasKey("Id")
                        .HasName("pk_asset_identifiers");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_asset_identifiers_asset_id");

                    b.HasIndex("IdentifierType", "IdentifierValue")
                        .HasDatabaseName("ix_asset_identifiers_identifier_type_identifier_value");

                    b.ToTable("asset_identifiers", "asset");
                });

            modelBuilder.Entity("CIOT.Modules.Asset.Domain.AssetOutletAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<Guid?>("OutletId")
                        .HasColumnType("uuid")
                        .HasColumnName("outlet_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("text")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<DateTime?>("UnassignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unassigned_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_asset_outlet_assignments");

                    b.HasIndex("AssetId", "IsCurrent")
                        .HasDatabaseName("ix_asset_outlet_assignments_asset_id_is_current");

                    b.ToTable("asset_outlet_assignments", "asset");
                });

            modelBuilder.Entity("CIOT.Modules.Asset.Domain.AssetWaterFilter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<decimal?>("CapacityUsedLiters")
                        .HasColumnType("numeric")
                        .HasColumnName("capacity_used_liters");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime?>("InstalledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_at_utc");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<DateTime?>("LastResetAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reset_at_utc");

                    b.Property<Guid?>("LastResetByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_reset_by_user_id");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("text")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("WaterFilterModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("water_filter_model_id");

                    b.HasKey("Id")
                        .HasName("pk_asset_water_filters");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_asset_water_filters_asset_id");

                    b.ToTable("asset_water_filters", "asset");
                });

            modelBuilder.Entity("CIOT.Modules.Asset.Domain.AssetIdentifier", b =>
                {
                    b.HasOne("CIOT.Modules.Asset.Domain.Asset", "Asset")
                        .WithMany("Identifiers")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_identifiers_assets_asset_id");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("CIOT.Modules.Asset.Domain.AssetOutletAssignment", b =>
                {
                    b.HasOne("CIOT.Modules.Asset.Domain.Asset", "Asset")
                        .WithMany("OutletAssignments")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_outlet_assignments_assets_asset_id");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("CIOT.Modules.Asset.Domain.AssetWaterFilter", b =>
                {
                    b.HasOne("CIOT.Modules.Asset.Domain.Asset", "Asset")
                        .WithMany("WaterFilters")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_water_filters_assets_asset_id");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("CIOT.Modules.Asset.Domain.Asset", b =>
                {
                    b.Navigation("Identifiers");

                    b.Navigation("OutletAssignments");

                    b.Navigation("WaterFilters");
                });
#pragma warning restore 612, 618
        }
    }
}
