<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.Identity.Web" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\CIOT.Common\CIOT.Common.csproj" />
    <ProjectReference Include="..\Domain\CIOT.Modules.Identity.Domain.csproj" />
  </ItemGroup>
</Project>
