// <auto-generated />
using System;
using CIOT.Modules.Telemetry.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CIOT.Modules.Telemetry.Infrastructure.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    partial class TelemetryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("telemetry")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CIOT.Modules.Telemetry.Domain.AssetCurrentState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<decimal?>("CoffeeKgToday")
                        .HasColumnType("numeric")
                        .HasColumnName("coffee_kg_today");

                    b.Property<decimal?>("ConnectivityQualityScore")
                        .HasColumnType("numeric")
                        .HasColumnName("connectivity_quality_score");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int?>("CupsToday")
                        .HasColumnType("integer")
                        .HasColumnName("cups_today");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<decimal?>("EnergyKwhToday")
                        .HasColumnType("numeric")
                        .HasColumnName("energy_kwh_today");

                    b.Property<DateTime>("LastTelemetryAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_telemetry_at_utc");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("MachineStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("machine_status");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("text")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("StateJson")
                        .HasColumnType("text")
                        .HasColumnName("state_json");

                    b.Property<decimal?>("WaterLitersToday")
                        .HasColumnType("numeric")
                        .HasColumnName("water_liters_today");

                    b.HasKey("Id")
                        .HasName("pk_asset_current_states");

                    b.HasIndex("AssetId")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_current_states_asset_id");

                    b.ToTable("asset_current_states", "telemetry");
                });

            modelBuilder.Entity("CIOT.Modules.Telemetry.Domain.NormalizedEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("EventOccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_occurred_at_utc");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("text")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.HasKey("Id")
                        .HasName("pk_normalized_events");

                    b.HasIndex("DeviceId", "EventType", "EventOccurredAtUtc")
                        .HasDatabaseName("ix_normalized_events_device_id_event_type_event_occurred_at_utc");

                    b.ToTable("normalized_events", "telemetry");
                });

            modelBuilder.Entity("CIOT.Modules.Telemetry.Domain.NormalizedMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<bool>("IsDerived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_derived");

                    b.Property<DateTime>("MeasuredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at_utc");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("metric_key");

                    b.Property<double>("NumericValue")
                        .HasColumnType("double precision")
                        .HasColumnName("numeric_value");

                    b.Property<Guid?>("OutletId")
                        .HasColumnType("uuid")
                        .HasColumnName("outlet_id");

                    b.Property<Guid?>("RawMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("raw_message_id");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("text")
                        .HasColumnName("unit_of_measure");

                    b.HasKey("Id")
                        .HasName("pk_normalized_measurements");

                    b.HasIndex("AssetId", "MetricKey", "MeasuredAtUtc")
                        .HasDatabaseName("ix_normalized_measurements_asset_id_metric_key_measured_at_utc");

                    b.HasIndex("DeviceId", "MetricKey", "MeasuredAtUtc")
                        .HasDatabaseName("ix_normalized_measurements_device_id_metric_key_measured_at_utc");

                    b.ToTable("normalized_measurements", "telemetry");
                });

            modelBuilder.Entity("CIOT.Modules.Telemetry.Domain.RawMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetIdentifier")
                        .HasColumnType("text")
                        .HasColumnName("asset_identifier");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DeviceIdentifier")
                        .HasColumnType("text")
                        .HasColumnName("device_identifier");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("message_id");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<string>("PayloadHash")
                        .HasColumnType("text")
                        .HasColumnName("payload_hash");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at_utc");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("text")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_raw_messages");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_raw_messages_message_id");

                    b.ToTable("raw_messages", "telemetry");
                });
#pragma warning restore 612, 618
        }
    }
}
