// <auto-generated />
using System;
using CIOT.Modules.CustomerOutlet.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CIOT.Modules.CustomerOutlet.Infrastructure.Migrations
{
    [DbContext(typeof(CustomerOutletDbContext))]
    [Migration("20260907115627_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("customer_outlet")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CIOT.Modules.CustomerOutlet.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("CustomerClusterId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_cluster_id");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customer_code");

                    b.Property<string>("CustomerName1")
                        .HasColumnType("text")
                        .HasColumnName("customer_name1");

                    b.Property<string>("CustomerName2")
                        .HasColumnType("text")
                        .HasColumnName("customer_name2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("text")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("VatNumber")
                        .HasColumnType("text")
                        .HasColumnName("vat_number");

                    b.Property<string>("WholesalerCode")
                        .HasColumnType("text")
                        .HasColumnName("wholesaler_code");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("CustomerClusterId")
                        .HasDatabaseName("ix_customers_customer_cluster_id");

                    b.HasIndex("CustomerCode")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_customer_code");

                    b.ToTable("customers", "customer_outlet");
                });

            modelBuilder.Entity("CIOT.Modules.CustomerOutlet.Domain.CustomerCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClusterCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cluster_code");

                    b.Property<string>("ClusterName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cluster_name");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("text")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.HasKey("Id")
                        .HasName("pk_customer_clusters");

                    b.HasIndex("ClusterCode")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_clusters_cluster_code");

                    b.ToTable("customer_clusters", "customer_outlet");
                });

            modelBuilder.Entity("CIOT.Modules.CustomerOutlet.Domain.CustomerRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<Guid>("PrimaryCustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_customer_id");

                    b.Property<Guid>("RelatedCustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_customer_id");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relationship_type");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("text")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.HasKey("Id")
                        .HasName("pk_customer_relationships");

                    b.ToTable("customer_relationships", "customer_outlet");
                });

            modelBuilder.Entity("CIOT.Modules.CustomerOutlet.Domain.Outlet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine")
                        .HasColumnType("text")
                        .HasColumnName("address_line");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<string>("OutletCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("outlet_code");

                    b.Property<string>("OutletType")
                        .HasColumnType("text")
                        .HasColumnName("outlet_type");

                    b.Property<string>("PayerCode")
                        .HasColumnType("text")
                        .HasColumnName("payer_code");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<Guid?>("SalesTerritoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_territory_id");

                    b.Property<string>("Seasonality")
                        .HasColumnType("text")
                        .HasColumnName("seasonality");

                    b.Property<string>("Segmentation")
                        .HasColumnType("text")
                        .HasColumnName("segmentation");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("text")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("SubTradeChannel")
                        .HasColumnType("text")
                        .HasColumnName("sub_trade_channel");

                    b.HasKey("Id")
                        .HasName("pk_outlets");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_outlets_customer_id");

                    b.HasIndex("OutletCode")
                        .IsUnique()
                        .HasDatabaseName("ix_outlets_outlet_code");

                    b.ToTable("outlets", "customer_outlet");
                });

            modelBuilder.Entity("CIOT.Modules.CustomerOutlet.Domain.OutletNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<string>("NoteBody")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note_body");

                    b.Property<Guid>("OutletId")
                        .HasColumnType("uuid")
                        .HasColumnName("outlet_id");

                    b.Property<Guid?>("RelatedAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_asset_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("text")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.HasKey("Id")
                        .HasName("pk_outlet_notes");

                    b.HasIndex("OutletId")
                        .HasDatabaseName("ix_outlet_notes_outlet_id");

                    b.ToTable("outlet_notes", "customer_outlet");
                });

            modelBuilder.Entity("CIOT.Modules.CustomerOutlet.Domain.Customer", b =>
                {
                    b.HasOne("CIOT.Modules.CustomerOutlet.Domain.CustomerCluster", "CustomerCluster")
                        .WithMany()
                        .HasForeignKey("CustomerClusterId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_customers_customer_clusters_customer_cluster_id");

                    b.Navigation("CustomerCluster");
                });

            modelBuilder.Entity("CIOT.Modules.CustomerOutlet.Domain.Outlet", b =>
                {
                    b.HasOne("CIOT.Modules.CustomerOutlet.Domain.Customer", "Customer")
                        .WithMany("Outlets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_outlets_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CIOT.Modules.CustomerOutlet.Domain.OutletNote", b =>
                {
                    b.HasOne("CIOT.Modules.CustomerOutlet.Domain.Outlet", "Outlet")
                        .WithMany("Notes")
                        .HasForeignKey("OutletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_outlet_notes_outlets_outlet_id");

                    b.Navigation("Outlet");
                });

            modelBuilder.Entity("CIOT.Modules.CustomerOutlet.Domain.Customer", b =>
                {
                    b.Navigation("Outlets");
                });

            modelBuilder.Entity("CIOT.Modules.CustomerOutlet.Domain.Outlet", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
