// <auto-generated />
using System;
using CIOT.Modules.Catalog.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CIOT.Modules.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CIOT.Modules.Catalog.Domain.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BusinessUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_unit_id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CustomerVat")
                        .HasColumnType("text")
                        .HasColumnName("customer_vat");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("material_code");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<string>("ProductBaseName")
                        .HasColumnType("text")
                        .HasColumnName("product_base_name");

                    b.Property<string>("ProductName")
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("text")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.HasKey("Id")
                        .HasName("pk_materials");

                    b.HasIndex("MaterialCode", "CountryCode")
                        .IsUnique()
                        .HasDatabaseName("ix_materials_material_code_country_code");

                    b.ToTable("materials", "catalog");
                });

            modelBuilder.Entity("CIOT.Modules.Catalog.Domain.SkuMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MappingType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mapping_type");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku_code");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("text")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.HasKey("Id")
                        .HasName("pk_sku_mappings");

                    b.HasIndex("SkuCode")
                        .IsUnique()
                        .HasDatabaseName("ix_sku_mappings_sku_code");

                    b.ToTable("sku_mappings", "catalog");
                });
#pragma warning restore 612, 618
        }
    }
}
