<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\CIOT.Common\CIOT.Common.csproj" />
    <ProjectReference Include="..\Domain\CIOT.Modules.LocalAdapter.Domain.csproj" />
    <ProjectReference Include="..\Infrastructure\CIOT.Modules.LocalAdapter.Infrastructure.csproj" />
  </ItemGroup>
</Project>
