// <auto-generated />
using System;
using CIOT.Modules.Mobile.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CIOT.Modules.Mobile.Infrastructure.Migrations
{
    [DbContext(typeof(MobileDbContext))]
    [Migration("20260906201341_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("mobile")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CIOT.Modules.Mobile.Domain.DeviceReplacement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<Guid>("NewDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("new_device_id");

                    b.Property<Guid>("OldDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("old_device_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime>("ReplacedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("replaced_at_utc");

                    b.Property<Guid>("ReplacedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_user_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("text")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.HasKey("Id")
                        .HasName("pk_device_replacements");

                    b.HasIndex("AssetId", "ReplacedAtUtc")
                        .HasDatabaseName("ix_device_replacements_asset_id_replaced_at_utc");

                    b.ToTable("device_replacements", "mobile");
                });

            modelBuilder.Entity("CIOT.Modules.Mobile.Domain.OfflineActionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_type");

                    b.Property<string>("ClientActionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_action_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<Guid>("OfflineBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("offline_batch_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("text")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.HasKey("Id")
                        .HasName("pk_offline_action_results");

                    b.HasIndex("OfflineBatchId", "ClientActionId")
                        .HasDatabaseName("ix_offline_action_results_offline_batch_id_client_action_id");

                    b.ToTable("offline_action_results", "mobile");
                });

            modelBuilder.Entity("CIOT.Modules.Mobile.Domain.OfflineBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActionCount")
                        .HasColumnType("integer")
                        .HasColumnName("action_count");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DeviceClientSessionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_client_session_id");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("text")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TechnicianUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("technician_user_id");

                    b.HasKey("Id")
                        .HasName("pk_offline_batches");

                    b.ToTable("offline_batches", "mobile");
                });

            modelBuilder.Entity("CIOT.Modules.Mobile.Domain.OfflineActionResult", b =>
                {
                    b.HasOne("CIOT.Modules.Mobile.Domain.OfflineBatch", null)
                        .WithMany("Results")
                        .HasForeignKey("OfflineBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_offline_action_results_offline_batches_offline_batch_id");
                });

            modelBuilder.Entity("CIOT.Modules.Mobile.Domain.OfflineBatch", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
