// <auto-generated />
using System;
using CIOT.Modules.Provisioning.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CIOT.Modules.Provisioning.Infrastructure.Migrations
{
    [DbContext(typeof(ProvisioningDbContext))]
    partial class ProvisioningDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("provisioning")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CIOT.Modules.Provisioning.Domain.AssetManufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("ManufacturerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("manufacturer_code");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("text")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_asset_manufacturers");

                    b.HasIndex("ManufacturerCode")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_manufacturers_manufacturer_code");

                    b.ToTable("asset_manufacturers", "provisioning");
                });

            modelBuilder.Entity("CIOT.Modules.Provisioning.Domain.DeviceAssetPairing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<DateTime>("PairedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paired_at_utc");

                    b.Property<string>("PairingStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pairing_status");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("text")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.HasKey("Id")
                        .HasName("pk_device_asset_pairings");

                    b.HasIndex("DeviceId", "AssetId")
                        .HasDatabaseName("ix_device_asset_pairings_device_id_asset_id");

                    b.ToTable("device_asset_pairings", "provisioning");
                });

            modelBuilder.Entity("CIOT.Modules.Provisioning.Domain.DeviceManufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("display_name");

                    b.Property<string>("ManufacturerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("manufacturer_code");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("text")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_device_manufacturers");

                    b.HasIndex("ManufacturerCode")
                        .IsUnique()
                        .HasDatabaseName("ix_device_manufacturers_manufacturer_code");

                    b.ToTable("device_manufacturers", "provisioning");
                });

            modelBuilder.Entity("CIOT.Modules.Provisioning.Domain.DeviceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("DeviceManufacturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_manufacturer_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("HardwareRevision")
                        .HasColumnType("text")
                        .HasColumnName("hardware_revision");

                    b.Property<string>("ModelCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_code");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("text")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_device_models");

                    b.HasIndex("DeviceManufacturerId")
                        .HasDatabaseName("ix_device_models_device_manufacturer_id");

                    b.HasIndex("ModelCode")
                        .IsUnique()
                        .HasDatabaseName("ix_device_models_model_code");

                    b.ToTable("device_models", "provisioning");
                });

            modelBuilder.Entity("CIOT.Modules.Provisioning.Domain.ManufacturerDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("DeviceModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_model_id");

                    b.Property<string>("Imei")
                        .HasColumnType("text")
                        .HasColumnName("imei");

                    b.Property<string>("MacAddress")
                        .HasColumnType("text")
                        .HasColumnName("mac_address");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<string>("ProvisioningStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provisioning_status");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_number");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("text")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.HasKey("Id")
                        .HasName("pk_manufacturer_devices");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_manufacturer_devices_serial_number");

                    b.ToTable("manufacturer_devices", "provisioning");
                });

            modelBuilder.Entity("CIOT.Modules.Provisioning.Domain.DeviceModel", b =>
                {
                    b.HasOne("CIOT.Modules.Provisioning.Domain.DeviceManufacturer", "DeviceManufacturer")
                        .WithMany("DeviceModels")
                        .HasForeignKey("DeviceManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_models_device_manufacturers_device_manufacturer_id");

                    b.Navigation("DeviceManufacturer");
                });

            modelBuilder.Entity("CIOT.Modules.Provisioning.Domain.DeviceManufacturer", b =>
                {
                    b.Navigation("DeviceModels");
                });
#pragma warning restore 612, 618
        }
    }
}
